charts/acp/.helmignore, charts/acp/Chart.yaml, charts/acp/templates/NOTES.txt, charts/acp/templates/_helpers.tpl, charts/acp/templates/deployment.yaml, charts/acp/templates/hpa.yaml, charts/acp/templates/ingress.yaml, charts/acp/templates/service.yaml, charts/acp/templates/serviceaccount.yaml, charts/acp/templates/tests/test-connection.yaml, charts/acp/values.yaml
Created with `helm create acp`.
=> acp: Define basic helm chart structure

charts/kube-acp-stack/.helmignore, charts/kube-acp-stack/Chart.yaml, charts/kube-acp-stack/templates/NOTES.txt, charts/kube-acp-stack/templates/_helpers.tpl, charts/kube-acp-stack/templates/deployment.yaml, charts/kube-acp-stack/templates/hpa.yaml, charts/kube-acp-stack/templates/ingress.yaml, charts/kube-acp-stack/templates/service.yaml, charts/kube-acp-stack/templates/serviceaccount.yaml, charts/kube-acp-stack/templates/tests/test-connection.yaml, charts/kube-acp-stack/values.yaml
Created with `helm create kube-acp-stack`.
=> kube-acp-stack: Define basic helm chart structure

charts/openbanking/templates/financroo/deployment.yaml, charts/openbanking/templates/import/configmap.yaml, charts/openbanking/values.yaml
=> Import fixes

charts/openbanking/templates/import/configmap.yaml, charts/openbanking/values.yaml
Client cert termination  settings support
=> added support  for client cert termination settings

charts/openbanking/Chart.yaml, charts/openbanking/templates/bank/configmap.yaml, charts/openbanking/values.yaml
This PR allows to overwrite the default bank mock data using values file.
I'm also bumping the version to have a released version
=> Allow to set bank's mock data via values

charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Bump acp and istio-authorizer to 1.12.2
=> Release acp 1.12.2

charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Updated charts for acp 1.14.0 release
=> Updated charts for acp 1.14.0 release

charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
We're adding the `disableTls` flag
=> Release 1.14.2

charts/acp/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Release ACP charts version 0.14.4 that includes client cert header config
=> Release acp charts version 0.14.4

charts/acp/Chart.yaml, charts/acp/README.md, charts/acp/values.yaml, charts/istio-authorizer/Chart.yaml, charts/istio-authorizer/README.md, charts/istio-authorizer/values.yaml, charts/kube-acp-stack/Chart.yaml, charts/kube-acp-stack/README.md
Updating registry secret name to the new `docker.cloudentity.io`
=> Update registry name to `docker.cloudentity.io`

charts/acp/Chart.yaml, charts/acp/README.md, charts/acp/templates/configmap.yaml, charts/acp/templates/fission.yaml, charts/acp/templates/serviceaccount.yaml, charts/acp/values.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Release 0.16.0 initial PR.
Tested locally using this checklist https://cloudentity.atlassian.net/wiki/spaces/QA/pages/2566586449/Acp+Helm+Charts+Release+Checklist+Steps 
While testing found this:
- https://cloudentity.atlassian.net/browse/AUT-4202
=> init release 0.16.0

charts/acp/Chart.yaml, charts/acp/templates/certificate.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Add missing helm parameters to values.yaml and update descriptions
[] Bugfix (non-breaking change which fixes an issue)
[] New feature (non-breaking change which adds functionality)
[] Tests (extending the test suite)
[X] Refactor (internal improvement that doesn't change product functionality)
[] Other (if none of the other choices apply)
=> [AUT-4021] add missing helm parameters

charts/acp/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Raised ACP chart version to 0.16.2 in order to release the new feature of mTLS Ingress.
=> [AUT-3741] Raised ACP chart version to 0.16.2

charts/acp/Chart.yaml, charts/acp/templates/import.yaml
Increase acp backoff limit from 4 to 8 as it sometimes fail for me with current setup (network speed).
=> Increase acp backoff limit from 4 to 8

charts/acp/Chart.yaml, charts/acp/templates/configmap.yaml, charts/kube-acp-stack/Chart.yaml, charts/kube-acp-stack/README.md, charts/kube-acp-stack/values.yaml
ACP was updated to support redis-cluster topology. This PR updates redis master-replica to redis multi master
=> AUT-3538/redis multi master

charts/acp/values.yaml
Drop the features from values.yaml
=> [DEVOPS-1585] Drop the features from values.yaml

charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Realising new version of our charts: `0.17.0` with ACP 1.17.0
=> [DEVOPS-1609] Raised ACP chart version to 0.17.0

charts/acp/Chart.yaml, charts/acp/templates/deployment.yaml, charts/acp/templates/import.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Add Security contexts according to k8s best practicies: https://aws.github.io/aws-eks-best-practices/security/docs/pods/
=> Aut 4934/update security values

charts/kube-acp-stack/Chart.yaml
=> [AUT-4951] cockroachdb bump to 7.0.0

charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Release 0.17.2-1

charts/acp/Chart.yaml, charts/acp/templates/fission.yaml, charts/acp/values.yaml, charts/istio-authorizer/Chart.yaml, charts/istio-authorizer/templates/deployment.yaml, charts/istio-authorizer/values.yaml
Add SecurityContexts to istio-authorizer and fission pods
=> AUT-4934/securitycontext

charts/acp/Chart.yaml, charts/acp/templates/fission.yaml
Bump rego env image that includes updated libraries.
=> Bump rego env image

charts/istio-authorizer/values.yaml
- add missing values to values.yam file
=> [DEVOPS-723] add additional values to values.yaml file

charts/istio-authorizer/Chart.yaml, charts/istio-authorizer/templates/policy.yaml, charts/istio-authorizer/values.yaml
Add flag to istio authorizer helm chart to disable/enable authorization policy (enabled by default)
=> Add flag to istio authorizer to disable/enable authorization policy

charts/istio-authorizer/Chart.yaml, charts/istio-authorizer/templates/deployment.yaml, charts/istio-authorizer/values.yaml
Needed to enable pprof profiling etc
=> Revert extra env vars in istio authorizer

charts/istio-authorizer/templates/deployment.yaml, charts/istio-authorizer/templates/hpa.yaml, charts/istio-authorizer/values.yaml
- add the possibility to deploy istio-authorizer as a daemon set
=> [AUT-5298] add possibility to deploy istio-authorizer as a daemonSet

.github/workflows/acp-test.yaml, .github/workflows/istio-authorizer-test.yaml, .github/workflows/kong-authorizer-test.yaml, .github/workflows/kube-acp-stack-test.yaml, .github/workflows/openbanking-test.yaml, .github/workflows/publish.yml, Makefile, charts/kube-acp-stack/Chart.yaml, tests/scripts/acp-version-check.sh
Adding `Makefile` and helm chart tests stub to further development.
For now each helm chart contains only Helm Lint check.
=> [AUT-5288] Added Makefile and test workflows stubs

charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
- acp chart release 0.17.2
- acp app update 1.17.1
- istio-authorizer chart release 1.17.11
=> Release acp 0.17.2 istio-authorizer 1.17.11

.github/workflows/acp-test.yaml, .github/workflows/istio-authorizer-test.yaml, .github/workflows/kong-authorizer-test.yaml, .github/workflows/kube-acp-stack-test.yaml, .github/workflows/openbanking-test.yaml, Dockerfile, Makefile
Check helm manifests for deprecations or removals or kubernetes APIs
=> Add check kube APIs

charts/istio-authorizer/Chart.yaml, charts/istio-authorizer/templates/configmap.yaml, charts/istio-authorizer/templates/deployment.yaml, charts/istio-authorizer/values.yaml
Istio authorizer - add more configuration options
Add `checksum/config` to restart authorizer on configmap changes
=> Istio authorizer - add more configuration options

.github/workflows/acp-test.yaml, .github/workflows/publish.yml, Makefile, charts/acp/templates/tests/get-access-token.yaml, tests/config/kind.yaml, tests/config/kube-acp-stack.yaml
Adding Helm test to the `acp` chart.
=> [AUT-5288] Added access token test to `acp` chart

.github/workflows/acp-cd-test.yaml, .github/workflows/publish.yml
=> [DEVOPS-723] acp-cd lint

charts/acp/Chart.yaml, charts/acp/templates/workers_service.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Add optional workers service to expose metrics endpoint
=> Add workers service

charts/istio-authorizer/Chart.yaml, charts/istio-authorizer/templates/configmap.yaml
Add missing configmap entry for enforcement in the istio authorizer
=> Add missing configmap entry for enforcement in the istio authorizer

charts/acp/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Release 2.0.1

charts/acp/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Release ACP chart version 2.0.1
=> Release acp 2.0.1

charts/istio-authorizer/templates/clusterrole.yaml
Add list namespaces cluster rule to istio authorizer to enable auto namespace service discovery.
=> [AUT-5490] Add permission to list namespaces to istio authorizer

charts/kong-authorizer/templates/deployment.yaml, charts/kong-authorizer/templates/hpa.yaml, charts/kong-authorizer/values.yaml
- Update HPA version.
- Add setting for topology.
- Replace deployAsDaemonSet with `autoscaling.enabled` to reduce the number of variables.
- [] Other (if none of the other choices apply)
=> [AUT-4909] Kong - update hpa version and allow topology setting

.github/workflows/istio-authorizer-test.yaml, .github/workflows/kong-authorizer-test.yaml, Makefile, charts/kong-authorizer/templates/configmap.yaml, charts/kong-authorizer/templates/tests/allow-request.yaml, charts/kong-authorizer/templates/tests/block-request.yaml, charts/kong-authorizer/values.yaml, tests/config/kong-authorizer.yaml, tests/config/kong.yaml, tests/config/kube-acp-stack.yaml
Added simple Kong-authorizer helm tests.
Tests not enabled in github work flow as changes from https://github.com/cloudentity/acp/pull/2644 are required to be published publicly for it to work.
=> [AUT-5290] Kong-authorizer helm tests

charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kong-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Release ACP chart version 2.0.2
=> Release ACP 2.0.2

charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kong-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
ACP Helm Charts - Release 2.1.0
=> Release 2.1.0

charts/acp/Chart.yaml, charts/acp/templates/deployment.yaml, charts/acp/templates/workers_deployment.yaml, charts/kube-acp-stack/Chart.yaml
Application migrations are now part of sql migrations and we can disable it
=> Add application migrations

Makefile, charts/acp/Chart.yaml, charts/acp/templates/pdb.yaml, charts/acp/templates/workers_pdb.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Add pod disruption budget support
=> Add pod disruption budget

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml, charts/openbanking/templates/consent-admin/ingress.yaml, charts/openbanking/templates/consent-page/ingress.yaml, charts/openbanking/templates/consent-self-service/ingress.yaml, charts/openbanking/templates/financroo/ingress.yaml, tests/services/httpbin/k8s-ingress.yaml
=> Release 2.2.0

charts/acp/templates/migration.yaml
- add possibility to mount configs for migrate jobs
=> [AUT-5623] add configs for sql migrate job

charts/acp/Chart.yaml, charts/kube-acp-stack/Chart.yaml
- bump chart version to 2.2.0-1
=> [AUT-5623] bump chart version

charts/acp/Chart.yaml, charts/kube-acp-stack/Chart.yaml
- bump chart version to 2.2.1-1
=> [AUT-5623] bump chart version 2.2.1-1

charts/acp/Chart.yaml, charts/acp/templates/migration.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
=> [AUT-5623] migration job configuration

charts/acp/Chart.yaml, charts/acp/templates/certificate.yaml, charts/acp/templates/migration.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
- adding commonName to certyficate
=> [AUT-5623] add cn to cert

tests/scripts/bump-acp-version.sh
Add git config settings to avoid git commit failures.
=> AUT-5740 Add git config settings

charts/acp/Chart.yaml, charts/acp/templates/certificate.yaml, charts/acp/templates/migration.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
- adding commonName to certyficate
=> [AUT-5623] add cn to certificate

charts/acp/Chart.yaml, charts/acp/templates/configmap.yaml, charts/acp/templates/deployment.yaml, charts/acp/templates/import.yaml, charts/acp/templates/migration.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
- Refacrtor migrateJob, importJob, and acp --config sections
=> [DEVOPS-1882] refactor for acp args, import and migrate jobs

charts/acp/Chart.yaml, charts/acp/templates/migration.yaml, charts/acp/templates/workers_deployment.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
- Refacrtor acp-worker configuration
=> [DEVOPS-1882] upgrade acp-worker configuration

charts/acp/templates/deployment.yaml, charts/acp/templates/import.yaml, charts/acp/templates/migration.yaml, charts/acp/templates/workers_deployment.yaml, charts/acp/values.yaml
- rename customConfig to configPath variable
=> [DEVOPS-723] rename customConfig co configPath

charts/acp/templates/fission.yaml
=> Bump fission envs

.github/workflows/release-branch.yaml, tests/scripts/bump-acp-version.sh
Add CI var. If set to "true", it will run git config, commit, and push after bumping helm chart versions.
Else, it'll just bump the helm chart versions.
=> [DEVOPS-723] Add CI var

charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Add missing part of chart acp kube chart.
=> Add missing part of chart acp kube chart.

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/acp/templates/fission.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Release 2.4.0

charts/acp/Chart.yaml, charts/acp/values.yaml, charts/istio-authorizer/Chart.yaml, charts/istio-authorizer/values.yaml, charts/kube-acp-stack/Chart.yaml
Update Security Contexts to more strict policies
=> Update Security Context

charts/acp/Chart.yaml, charts/acp/templates/configmap.yaml, charts/kube-acp-stack/Chart.yaml
If certManager is used, set proper certs paths in ACP config
If certManager is used and no ACP client CA provided, use the one from certManager
=> [AUT-6830] Certmanager fix config

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Release of ACP 2.6.0

charts/kube-acp-stack/Chart.yaml
- redis upgrade to 7.6.4
- cockroachdb 8.1.6
=> [AUT-7130] redis and cockroachdb upgrade

charts/kube-acp-stack/Chart.yaml
Reverts cloudentity/acp-helm-charts#213
=> Revert "[AUT-7130] redis and cockroachdb upgrade"

.github/workflows/acp-test.yaml, charts/kube-acp-stack/Chart.yaml
- include istio and kube-acp-stack test to acp workflow
=> [DEVOPS-2210] update workflow logic

charts/acp/Chart.yaml, charts/acp/templates/deployment.yaml, charts/acp/templates/service.yaml, charts/kube-acp-stack/Chart.yaml
Configure grpc port at 50051 for spicedb.
=> [AUT-7149] Configure grpc port

charts/acp/Chart.yaml, charts/acp/templates/configmap.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Add fission provider value. This is required to support `hybrid` faas mode.
=> Add fission provider

charts/kube-acp-stack/Chart.yaml
- ccdb upgrade 8.1.0
- redis upgrade 7.6.4
=> [AUT-7130] upgrade ccdb and redis

.github/PULL_REQUEST_TEMPLATE.md
- pull request template update
=> pull request template update

.github/PULL_REQUEST_TEMPLATE.md
- pull request template update
=> [DEVOPS-2220] pull request template update

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/acp/README.md, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.8.0

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.8.1

charts/acp/Chart.yaml, charts/acp/templates/fission.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Updated rego environment for fission to the newest version.
Additionally allowing to configure fission env images from values
=> Allow to configure fission environment images in values, bump rego environment

charts/acp/Chart.yaml, charts/acp/templates/import.yaml, charts/acp/templates/migration.yaml, charts/kube-acp-stack/Chart.yaml
* Add hooks execution on `helm rollback`
* Add `ttlSecondsAfterFinished` to keep finished jobs for 1 day
=> Update job hooks

charts/acp/Chart.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
=> Fix fission registry

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Bump ACP version to 2.10.0 (release)
=> Bump acp version to 2.10.0

charts/kube-acp-stack/Chart.yaml, charts/kube-acp-stack/README.md, charts/kube-acp-stack/values.yaml, tests/config/kube-acp-stack.yaml, tests/config/timescale-role-binding.yaml
=> fix for timescaledb forbidden error

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Release 2.11.0

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Release 2.12.0

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.13.0

charts/acp/Chart.yaml, charts/acp/templates/configmap.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml, charts/kube-acp-stack/README.md, charts/kube-acp-stack/values.yaml, tests/config/timescale-role-binding.yaml
* Update cockroach dependency for chart to work on kube 1.25+
* Remove duplicated timescale section in values and configmap
* Move kube-acp-stack database url configuration from configmap into chart values
=> Fix databases config

tests/scripts/bump-acp-version.sh
Fix release pipeline by adding fetch step
=> Add fetch step

tests/scripts/bump-acp-version.sh
Fix release pipeline by adding stash step
=> Add stash step

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml, tests/scripts/bump-acp-version.sh
=> Release 2.14.0

charts/kube-acp-stack/values.yaml
=> Bump redisearch

charts/acp/values.yaml
Bump rego-env docker image to fix CVEs
=> [AUT-9199] Bump rego-env docker image to fix CVEs

.github/HELM_VALUE_UPDATE_PULL_REQUEST_TEMPLATE.md, .github/workflows/update-helm-chart-default-values.yaml
A simple GitHub action that could be triggered to update the default values of Helm charts.
=> DEVOPS-2516 Automate builds of rego-env and node-env docker images 

.github/HELM_VALUE_UPDATE_PULL_REQUEST_TEMPLATE.md, .github/workflows/update-helm-chart-default-values.yaml
FIx to my previous PR: https://github.com/cloudentity/acp-helm-charts/pull/256
=> DEVOPS-2561 Add missing checkout step

charts/openbanking/templates/consent-admin/deployment.yaml, charts/openbanking/templates/consent-page/deployment.yaml, charts/openbanking/templates/consent-self-service/deployment.yaml, charts/openbanking/templates/financroo/deployment.yaml
Fix service account names in OB charts
=> Fix service account names in OB charts

.github/HELM_VALUE_UPDATE_PULL_REQUEST_TEMPLATE.md, .github/workflows/update-helm-chart-default-values.yaml
Added a dedicated `CLOUDENTITY_CI_TOKEN` to improve security + missing step responsible for pushing to a custom branch.
=> DEVOPS-2561 Refactorization of the update-helm-chart-default-values GitHub action

charts/acp-cd/values.yaml, charts/acp/values.yaml
Reflecting documentation changes (migration of the reference config from the Operations Docs to the Developer Portal).
=> Update the reference config documentation URL

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/acp/values.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.15.0

charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/acp/README.md, charts/acp/values.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
Release a patch with rolled back node-env version update.
=> Rollback node-env version update.

.github/workflows/update-helm-chart-default-values.yaml
Introducing a step responsible for keeping empty lines in place, as per https://github.com/mikefarah/yq/issues/515
=> DEVOPS-2561 Fix formatting by keeping empty lines

charts/acp/values.yaml
This pull request has been created automatically.
We kindly request that you review and approve this pull request as soon as possible to ensure a seamless transition of these changes.
=> [acp] Update default value of .fission.images.node

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.16.0

charts/acp/Chart.yaml, charts/acp/templates/fission.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
- update fission function startup, readiness, and liveness to fix edge condition, where ACP hangs waiting for the fission function - startupProbe adjustment needed
=> [DEVOPS-723] startupProbe for fission envs update

charts/kube-acp-stack/values.yaml
Upgrading the Redisearch module to make it in line with our internal configuration.
=> AUT-9625 Upgrade redisearch module

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.17.0

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> AUT-3987 Bump acp version to 2.18.0

charts/acp/Chart.yaml, charts/acp/templates/fission.yaml, charts/kube-acp-stack/Chart.yaml
Allow pre warmed pool size adjustments
=> Bump environment version

charts/acp-cd/Chart.yaml, charts/acp-cd/templates/_helpers.tpl, charts/acp-cd/templates/certificate.yaml, charts/acp-cd/templates/configmap.yaml, charts/acp-cd/templates/import.yaml, charts/acp-cd/templates/serviceaccount.yaml, charts/acp-cd/templates/tls-secrets.yaml, charts/acp-cd/values.yaml
Upgrade acp-cd chart to modern standards
* add serviceAccount
* add nodeSelector, affinity, tolerations, resources
* add cert-manager integration
* add missing parameters in values file
=> Upgrade acp-cd chart

charts/acp/values.yaml
Update default security context for fission containers by seccompProfile.
=> [DEVOPS-2668] Update container security context for fission

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/acp/values.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.19.0

charts/acp/Chart.yaml, charts/acp/templates/service.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Add possibility to disable ACP service
=> Add service switch

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.20.0

charts/acp/Chart.yaml, charts/acp/templates/_helpers.tpl, charts/acp/templates/configmap.yaml, charts/acp/templates/faas_deployment.yaml, charts/acp/templates/faas_hpa.yaml, charts/acp/templates/faas_keda.yaml, charts/acp/templates/faas_service.yaml, charts/acp/templates/fission.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Update environments key from integer to string as it causes issues while parsing yaml files
=> Update faas templates

charts/acp/Chart.yaml, charts/acp/templates/_helpers.tpl, charts/acp/templates/faas_deployment.yaml, charts/acp/templates/fission.yaml, charts/acp/values.yaml, charts/kube-acp-stack/Chart.yaml
Fix imagePullSecrets naming and missing "v" for node multi env url
=> Fix naming

.github/workflows/update-helm-chart-default-values.yaml
Standardize usage of commit and create pull request action across all pipelines
=> Standarize usage of PR action

.github/workflows/update-helm-chart-default-values.yaml, .github/workflows/update-helm-chart-faas-images.yaml
Update commit message for automated PRs
=> Update commit message

charts/istio-authorizer/templates/configmap.yaml, charts/istio-authorizer/values.yaml
Add a new configuration for token exchange in Istio authorizer to control what scopes are requested for a new token.
=> [AUT-10815] Add requestScopes token exchange configuration for istio authorizer

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/istio-authorizer/templates/configmap.yaml, charts/istio-authorizer/values.yaml, charts/kube-acp-stack/Chart.yaml
=> Bump acp version to 2.21.0

.github/workflows/release-branch.yaml
Adjust values to match acp trigger changes in release process.
=> [AUT-10818] Adjust values to match acp trigger changes

charts/kube-acp-stack/README.md
Deprecate kube-acp-stack helm in favour of acp-on-k8s repository
=> Add deprecation note

charts/acp/Chart.yaml, charts/acp/templates/faas_keda.yaml, charts/kube-acp-stack/Chart.yaml
Update KEDA CRD definition to match changes in [version 0.8.0](https://github.com/kedacore/http-add-on/releases/tag/v0.8.0)
=> Update KEDA CRD

.github/workflows/update-helm-chart-faas-images.yaml
failed acp-faas pipeline build https://jenkins.secureauth.tools/blue/organizations/jenkins/oauth%2Ffission-envs/detail/release%2F2.23.0/4/pipeline/
here is the fix
=> fix Update FaaS Images pipeline

Makefile, charts/acp-cd/Chart.yaml, charts/acp/Chart.yaml, charts/istio-authorizer/Chart.yaml, charts/kube-acp-stack/Chart.yaml, charts/kube-acp-stack/values.yaml
=> Bump acp version to 2.23.0

.github/workflows/update-helm-chart-faas-images.yaml
=> Fix GitHub actions
