cloudentity/acp-helm-charts

charts/acp/README.md

It seems that the repo url was incorrect.
Fixed it to point to acp.artifactory.cloudentity.com

Fixed Artifactory URL in Readme

---

charts/openbanking/templates/import/configmap.yaml
charts/openbanking/templates/import/job.yaml

This PR allows to define `extraTemplate` in value which the import configuration application will use to import additional clients/servers etc.

Extra templates support

---

charts/openbanking/templates/import/configmap.yaml
charts/openbanking/templates/import/job.yaml

Use PEM file as a source of JWKs used by financroo.
This is based on the recent changes introduced in openbanking-quickstart allowing to do the pem -> jwks convertion.

use pem file as a source for financroo jwks

---

charts/acp/Chart.yaml
charts/acp/templates/import.yaml
charts/acp/values.yaml

Add importJob customization options
* Fix missing securityContext (job cannot read tls config file to connect to crdb)
* Add options to set custom importjob args (for custom config names like /secret/secret.yaml instead /secret/config.yaml)
* Use same ENVS as ACP (to set crdb uri etc)
* Add resource definitions
* Use same selectors as ACP

Add import jobs options

---

charts/acp/templates/NOTES.txt
charts/acp/templates/_helpers.tpl
charts/acp/templates/configmap.yaml
charts/acp/templates/deployment.yaml
charts/acp/templates/ingress.yaml
charts/acp/templates/service.yaml
charts/acp/values.yaml

Jira issue: [DEVOPS-1448](https://cloudentity.atlassian.net/browse/DEVOPS-1448)
This feature adds `disableTls` option (with `false` default value) to the ACP helm chart.
If the option is set to `true`, ACP port number and protocol will change to HTTP values (no TLS).

[DEVOPS-1448] Added 'disableTls' flag to acp chart values

---

charts/acp/templates/configmap.yaml
charts/kube-acp-stack/Chart.yaml
charts/kube-acp-stack/README.md
charts/kube-acp-stack/values.yaml

BREAKING CHANGE. Redis was replaced by redis-cluster
- general:
- updated README
- kube-acp-stack:
- Dependencies:
- Update cockroachdb helm chart from 5.0.7 to 6.2.8
- Removed redis helm chart
- Added redis-cluster helm chart version 7.0.9
- Add redisearch module 2.2.0
- Enable redis password authentication
- Added redis password authentication
- Enable redis_search
- ACP:
- Update default values for redis connection uri
- Update default values for cockroachdb connection uri

AUT-3538/update redis

---

charts/acp/templates/ingress.yaml

This PR increases the ssl_verify_depth for client certs to 2. This is required to support OpenBanking Brazil.
The certs used by clients now include root_ca and the default value of `1` wasn't able to read the whole certificate and returned a 400.

update ssl_verify_depth to support longer cert chains

---

charts/acp/Chart.yaml
charts/kube-acp-stack/Chart.yaml

We've noticed a problem when trying to start `acp-on-k8s`.
Updated imagePullSecrets were not respected.
It turned out that `kube-acp-stack` helm charts were referencing  0.15.0 instead of 0.15.1
This PR bumps both `acp` and `kube-acp-stack` so charts will get updated.
[x] Bugfix (non-breaking change which fixes an issue)
[] New feature (non-breaking change which adds functionality)
[] Tests (extending the test suite)
[] Refactor (internal improvement that doesn't change product functionality)
[] Other (if none of the other choices apply)

bump acp helm version to 0.15.2

---

charts/acp/Chart.yaml
charts/acp/templates/configmap.yaml
charts/kube-acp-stack/Chart.yaml
charts/kube-acp-stack/README.md
charts/kube-acp-stack/values.yaml

If upgrading from version 0.15.0-0.15.2 will recreate redis cluster with data loss.
ACP is not fully compatible with redis open source multi master topology. ACP might randomly fail to connect to redis nodes. Minimum number of nodes in redis-cluster is 3 so we cannot scale it down to 1. We have decided to revert back redis-cluster change to redis master-replica which will result to cluster recreation while upgrading from 0.15.0 - 0.15.2. This does not affect users upgrading from 0.14.x. The issue will be resolved in upcoming ACP release.
[] Bugfix (non-breaking change which fixes an issue)
[] New feature (non-breaking change which adds functionality)
[] Tests (extending the test suite)
[] Refactor (internal improvement that doesn't change product functionality)
[x] Other (if none of the …

Revert redis-cluster

---

charts/acp/templates/ingress.yaml
charts/acp/templates/tls-secrets.yaml
charts/acp/values.yaml

Added possibility to enable additional Ingress running in mutual TLS (mTLS) mode to the ACP chart.

[AUT-3741] Added mTLS Ingress in ACP chart

---

charts/acp/templates/configmap.yaml
charts/acp/templates/ingress.yaml
charts/acp/values.yaml

mTLS Ingress for ACP has relaxed requirements for the client certificate now. The new nginx conf:
```
ssl_verify_client                       optional_no_ca;
```

[AUT-3741] Corrected Ingresses configuration for mTLS

---

charts/acp/templates/tls-secrets.yaml

Removed client ca secret type (default is opaque).
Current setup fails on install with
```
failed to create resource: Secret "acp-client-tls" is invalid: [data[tls.crt]: Required value, data[tls.key]: Required value]                                                                      
```
as tls secret type enforces
```
data:
tls.crt:
tls.key: 
```

[DEVOPS-1586] Replaced client ca secret type with default opaque

---

charts/istio-authorizer/Chart.yaml
charts/istio-authorizer/values.yaml

For on-prem deployments, until ACP 2.0 is released, the token exchange must be explicitly enabled in the authorizer.
- [] New feature (non-breaking change which adds functionality)

Bump istio authorizer with token exchange flag

---

.github/workflows/publish.yml

Removed old, unnecessary dependency on non exiting `lint` job in Publish workflow.

[DEVOPS-723] Removed github workflow dependency on lint in publish

---

.github/workflows/release-branch.yaml
tests/scripts/bump-acp-version.sh

Update release start scripts to also set charts app version as it was not set.

[DEVOPS-2101] Update release start scripts to also set charts app version

---

charts/acp/Chart.yaml
charts/acp/templates/ingress.yaml
charts/acp/values.yaml
charts/kube-acp-stack/Chart.yaml
tests/config/kind.yaml

Update ingress annotations with the following:
* Enable mod security with owasp by default
* Enable mTLS communication between ingress (nginx) and ACP
* Set downstream to ACP service instead of individual pods
Set kube version in tests to 1.24 as on newer version cockroachdb subchart that we use is failing to install due depreciated APIs.

Update nginx annotations

---

Makefile
charts/acp/templates/configmap.yaml
charts/acp/values.yaml

Allow setup of timescale values like:
```yaml
acp:
enabled: true
secretConfig:
data:
redis:
password: p@ssw0rd!
timescale:
enabled: true
url: postgres://acp:PaSsW0rD@timescaledb.acp-db.svc.cluster.local/acpdb
migrations:
path: ./migrations/timescale
timeout: 1m0s
```
instead of old way
```yaml
acp:
enabled: true
secretConfig:
data:
redis:
password: p@ssw0rd!
config:
data:
redis:
redis_search: true
timescale:
enabled: true
url: postgres://acp:PaSsW0rD@timescaledb.acp-db.svc.cluster.local/acpdb
migrations:
path: ./migrations/timescale
timeout: 1m0s
```

[DEVOPS-723] Setup of direct set values for timescaledb

---

charts/acp/templates/service.yaml
charts/acp/values.yaml

Add the possibility to annotate ACP service.
This is introduced as part of Contour testing as potential ingress, which requires specific annotation on service.

[AUT-8465] Add posibility to annotate acp service

---

charts/acp/templates/deployment.yaml
charts/acp/templates/fission.yaml
charts/acp/values.yaml

- define startupProbe, readinessProbe, livenessProbe:
1. deploy ACP stack from helm charts: 
- check if startup/liveness/readiness probes are available
- configure custom startup/liveness/readiness probes
2. deploy the fission component
- check if startup/liveness/readiness probes are available
- configure custom startup/liveness/readiness probes

[DEVOPS-2588] define startupProbe, readinessProbe, livenessProbe

---

charts/acp/Chart.yaml
charts/acp/values.yaml
charts/kube-acp-stack/Chart.yaml

Change acp deployment to restrict seccomp strict by default based on kyverno findings https://kyverno.io/policies/pod-security/restricted/restrict-seccomp-strict/restrict-seccomp-strict/

[DEVOPS-2667] Change acp deployment to restrict seccomp strict by default

---

charts/acp-cd/Chart.yaml
charts/acp-cd/templates/import.yaml
charts/acp-cd/values.yaml

Add the possibility to set container security context for the acp-cd chart and set default values.
Add possibility to set container security context for acp-cd and set default values in order to comply with security standards.

[DEVOPS-2622] Add possibility to set container security context for acp-cd and set default values

---

.github/workflows/update-helm-chart-faas-images.yaml
charts/acp/values.yaml

Add pipeline responsible for bumping faas image and packages

FaaS update pipeline

---

charts/istio-authorizer/Chart.yaml
charts/istio-authorizer/templates/clusterrole.yaml
charts/istio-authorizer/templates/clusterrolebinding.yaml

Changes in the istio authorizer:
Remove system:auth-delegator role as it's no longer required.
Apply ClusterRole for scanning namespaces and deployments only if discovery is enabled.

[AUT-10826] Istio authorizer cluster roles adjustments

---

.github/workflows/update-helm-chart-faas-images.yaml
Makefile
charts/acp-cd/Chart.yaml
charts/acp-cd/README.md
charts/acp-cd/values.yaml
charts/acp/Chart.yaml
charts/acp/README.md
charts/acp/values.yaml
charts/istio-authorizer/Chart.yaml
charts/istio-authorizer/README.md
charts/istio-authorizer/templates/dockerregistry.yaml
charts/istio-authorizer/values.yaml
charts/kube-acp-stack/Chart.yaml
charts/kube-acp-stack/README.md

Reflecting the recent changes related to the docker registries consolidation.

Update Docker registry references from docker.cloudentity.io to docker.secureauth.com

---

Makefile
charts/acp-cd/Chart.yaml
charts/acp/Chart.yaml
charts/istio-authorizer/Chart.yaml
charts/kube-acp-stack/Chart.yaml
charts/kube-acp-stack/values.yaml
tests/config/kind.yaml

- release acp 2.25.0
- it looks like PR is green but we need to wait for @jkotiuk 's task to bump redis https://secureauth.atlassian.net/browse/AUT-12336
- some additive changes needed in configuration in order to have stable stack with bumped redis. For sure Kuba knows the details :)

Bump acp version to 2.25.0
